version: "3.2"

services:

  nginx:
    build: './docker/nginx'
    container_name: docker-compose-nginx
    ports:
      - '8080:80'
    volumes:
      - ./public:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: './docker/php'
    container_name: docker-compose-php
    ports:
      - '9000:9000'
    volumes:
      - ./public:/app
    
