version: "3.2"
services:

  nginx:
    build: './docker/nginx'
    container_name: docker-compose-nginx
    ports:
      - '80:80'
    volumes:
      - ./public:/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: './docker/php'
    container_name: docker-compose-php
    ports:
      - '9000:9000'
    volumes:
      - ./public:/app

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: docker-compose-jenkins
    environment:
      - TZ="Europe/Minsk"
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - "./jenkins_data1:/var/jenkins_home"    
